fork = true
frame = "buttonless"
srgb = true
tabs = false
vsync = true
title-hidden = true

[font]
normal = "ComicCodeLigatures Nerd Font"
size = 15.0

[box-drawing]
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 10]

